### ISSUE TITLE
install CM

### ISSUE THREAD

**Issue by ona2** [ona2/SEBC#9]

**Comment by ona2** [comment]
cannot run ./scm_prepare_database.sh on CM node

Verifying that we can write to /etc/cloudera-scm-server
[                          main] DbProvisioner                  ERROR Exception when creating/dropping database with user 'root' and jdbc url 'jdbc:mysql://localhost/?useUnicode=true&characterEncoding=UTF-8'
com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.

**Comment by mfernest** [comment]
It appears you ended up deploying CM and MySQL on the same instance. There are also some messy details when connecting to MySQL from a remote host, which may have bitten you here.
